# Cleaning Data

## Importing Libraries
This section is for importing libraries for data importation and data reading.

In [33]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
from google.colab import files

In [3]:
ccbd_visualization = pd.read_csv('/content/Covid cases by day (visualizations).csv')
ccbd_country = pd.read_csv('/content/Covid cases by day and country.csv')
ccpc = pd.read_csv('/content/Covid cases per country.csv')
symptoms = pd.read_csv('/content/Covid symptoms.csv')
iso = pd.read_csv('/content/iso.csv')
worldometer_data = pd.read_csv('/content/worldometer_data.csv')

## Missing Data
This section will address the missing values from these tables. Missing values can cause error in data analysis.

### Covid cases by day (visualization)

In [ ]:
ccbd_visualization.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188 entries, 0 to 187
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    188 non-null    object
 1   Confirmed               188 non-null    int64
 2   Deaths                  188 non-null    int64
 3   Recovered               188 non-null    int64
 4   Active                  188 non-null    int64
 5   New cases               188 non-null    int64
 6   New deaths              188 non-null    int64
 7   New recovered           188 non-null    int64
 8   Deaths / 100 Cases      188 non-null    float64
 9   Recovered / 100 Cases   188 non-null    float64
 10  Deaths / 100 Recovered  188 non-null    float64
 11  No. of countries        188 non-null    int64
dtypes: float64(3), int64(8), object(1)
memory usage: 17.8+ KB

In [ ]:
ccbd_visualization.isna().sum()

Date                      0
Confirmed                 0
Deaths                    0
Recovered                 0
Active                    0
New cases                 0
New deaths                0
New recovered             0
Deaths / 100 Cases        0
Recovered / 100 Cases     0
Deaths / 100 Recovered    0
No. of countries          0
dtype: int64

No null values in covid cases by day (visualization).

### Covid cases by day and country

In [ ]:
ccbd_country.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35156 entries, 0 to 35155
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            35156 non-null  object
 1   Country/Region  35156 non-null  object
 2   Confirmed       35156 non-null  int64
 3   Deaths          35156 non-null  int64
 4   Recovered       35156 non-null  int64
 5   Active          35156 non-null  int64
 6   New cases       35156 non-null  int64
 7   New deaths      35156 non-null  int64
 8   New recovered   35156 non-null  int64
 9   WHO Region      35156 non-null  object
dtypes: int64(7), object(3)
memory usage: 2.7+ MB

In [ ]:
ccbd_country.isna().sum()

Date              0
Country/Region    0
Confirmed         0
Deaths            0
Recovered         0
Active            0
New cases         0
New deaths        0
New recovered     0
WHO Region        0
dtype: int64

There are no null values in Covid cases by day and country.

### Covid cases per country

In [ ]:
ccpc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Country/Region          187 non-null    object
 1   Confirmed               187 non-null    int64
 2   Deaths                  187 non-null    int64
 3   Recovered               187 non-null    int64
 4   Active                  187 non-null    int64
 5   New cases               187 non-null    int64
 6   New deaths              187 non-null    int64
 7   New recovered           187 non-null    int64
 8   Deaths / 100 Cases      187 non-null    float64
 9   Recovered / 100 Cases   187 non-null    float64
 10  Deaths / 100 Recovered  187 non-null    float64
 11  Confirmed last week     187 non-null    int64
 12  1 week change           187 non-null    int64
 13  1 week % increase       187 non-null    float64
 14  WHO Region              187 non-null    object
dtypes: float64(4), int64(9), object(2)
memory usage: 22.0+ KB

In [ ]:
ccpc.isna().sum()

Country/Region            0
Confirmed                 0
Deaths                    0
Recovered                 0
Active                    0
New cases                 0
New deaths                0
New recovered             0
Deaths / 100 Cases        0
Recovered / 100 Cases     0
Deaths / 100 Recovered    0
Confirmed last week       0
1 week change             0
1 week % increase         0
WHO Region                0
dtype: int64

There are no null values in covid cases per country.

### Covid symptoms

In [ ]:
symptoms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 316800 entries, 0 to 316799
Data columns (total 27 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Fever                    316800 non-null  int64
 1   Tiredness                316800 non-null  int64
 2   Dry-Cough                316800 non-null  int64
 3   Difficulty-in-Breathing  316800 non-null  int64
 4   Sore-Throat              316800 non-null  int64
 5   None_Sympton             316800 non-null  int64
 6   Pains                    316800 non-null  int64
 7   Nasal-Congestion         316800 non-null  int64
 8   Runny-Nose               316800 non-null  int64
 9   Diarrhea                 316800 non-null  int64
 10  None_Experiencing        316800 non-null  int64
 11  Age_0-9                  316800 non-null  int64
 12  Age_10-19                316800 non-null  int64
 13  Age_20-24                316800 non-null  int64
 14  Age_25-59                316800 non-null  int64
 15  Age_60+                  316800 non-null  int64
 16  Gender_Female            316800 non-null  int64
 17  Gender_Male              316800 non-null  int64
 18  Gender_Transgender       316800 non-null  int64
 19  Severity_Mild            316800 non-null  int64
 20  Severity_Moderate        316800 non-null  int64
 21  Severity_None            316800 non-null  int64
 22  Severity_Severe          316800 non-null  int64
 23  Contact_Dont-Know        316800 non-null  int64
 24  Contact_No               316800 non-null  int64
 25  Contact_Yes              316800 non-null  int64
 26  Country                  316800 non-null  object
dtypes: int64(26), object(1)
memory usage: 65.3+ MB

In [ ]:
symptoms.isna().sum()

Fever                      0
Tiredness                  0
Dry-Cough                  0
Difficulty-in-Breathing    0
Sore-Throat                0
None_Sympton               0
Pains                      0
Nasal-Congestion           0
Runny-Nose                 0
Diarrhea                   0
None_Experiencing          0
Age_0-9                    0
Age_10-19                  0
Age_20-24                  0
Age_25-59                  0
Age_60+                    0
Gender_Female              0
Gender_Male                0
Gender_Transgender         0
Severity_Mild              0
Severity_Moderate          0
Severity_None              0
Severity_Severe            0
Contact_Dont-Know          0
Contact_No                 0
Contact_Yes                0
Country                    0
dtype: int64

There are no null values in covid symptoms table.

### ISO

In [ ]:
iso.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 627920 entries, 0 to 627919
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   UID             627920 non-null  int64
 1   iso2            627920 non-null  object
 2   iso3            627920 non-null  object
 3   code3           627920 non-null  int64
 4   FIPS            626040 non-null  float64
 5   Admin2          626792 non-null  object
 6   Province_State  627920 non-null  object
 7   Country_Region  627920 non-null  object
 8   Lat             627920 non-null  float64
 9   Long_           627920 non-null  float64
 10  Combined_Key    627920 non-null  object
 11  Date            627920 non-null  object
 12  Confirmed       627920 non-null  int64
 13  Deaths          627920 non-null  int64
dtypes: float64(3), int64(4), object(7)
memory usage: 67.1+ MB

In [ ]:
iso.isna().sum()

UID                  0
iso2                 0
iso3                 0
code3                0
FIPS              1880
Admin2            1128
Province_State       0
Country_Region       0
Lat                  0
Long_                0
Combined_Key         0
Date                 0
Confirmed            0
Deaths               0
dtype: int64

There are null values in ISO table. However, as these are not random values, I cannot randomly replace them with mean or random values. And missing rows are significantly less than the total number of rows, so I dropped them. FIPS and Admins are not replacable values.

In [ ]:
iso.dropna(inplace=True)

In [ ]:
iso.info()

<class 'pandas.core.frame.DataFrame'>
Index: 624912 entries, 3 to 627908
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   UID             624912 non-null  int64
 1   iso2            624912 non-null  object
 2   iso3            624912 non-null  object
 3   code3           624912 non-null  int64
 4   FIPS            624912 non-null  float64
 5   Admin2          624912 non-null  object
 6   Province_State  624912 non-null  object
 7   Country_Region  624912 non-null  object
 8   Lat             624912 non-null  float64
 9   Long_           624912 non-null  float64
 10  Combined_Key    624912 non-null  object
 11  Date            624912 non-null  object
 12  Confirmed       624912 non-null  int64
 13  Deaths          624912 non-null  int64
dtypes: float64(3), int64(4), object(7)
memory usage: 71.5+ MB

### Worldometer Data

In [ ]:
worldometer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country/Region    209 non-null    object
 1   Continent         208 non-null    object
 2   Population        208 non-null    float64
 3   TotalCases        209 non-null    int64
 4   NewCases          4 non-null      float64
 5   TotalDeaths       188 non-null    float64
 6   NewDeaths         3 non-null      float64
 7   TotalRecovered    205 non-null    float64
 8   NewRecovered      3 non-null      float64
 9   ActiveCases       205 non-null    float64
 10  Serious,Critical  122 non-null    float64
 11  Tot Cases/1M pop  208 non-null    float64
 12  Deaths/1M pop     187 non-null    float64
 13  TotalTests        191 non-null    float64
 14  Tests/1M pop      191 non-null    float64
 15  WHO Region        184 non-null    object
dtypes: float64(12), int64(1), object(3)
memory usage: 26.3+ KB

Continent missing row gives "diamond princess" region, which does not exist. Thus, missing continent will be replaced with unknown since its a ship.

In [4]:
worldometer_data['Continent'] = worldometer_data['Continent'].fillna('Unknown')
worldometer_data['WHO Region'] = worldometer_data['WHO Region'].fillna('Unknown')

In [12]:
zero_fill_cols = [
    'NewCases', 'TotalDeaths', 'NewDeaths', 'TotalRecovered',
    'NewRecovered', 'ActiveCases', 'Serious,Critical', 'TotalTests'
]
worldometer_data[zero_fill_cols] = worldometer_data[zero_fill_cols].fillna(0)

worldometer_data['Tot Cases/1M pop'] = (worldometer_data['TotalCases'] / worldometer_data['Population']) * 1_000_000
worldometer_data['Deaths/1M pop'] = (worldometer_data['TotalDeaths'] / worldometer_data['Population']) * 1_000_000
worldometer_data['Tests/1M pop'] = (worldometer_data['TotalTests'] / worldometer_data['Population']) * 1_000_000

worldometer_data.replace([np.inf, -np.inf], 0, inplace=True)
worldometer_data['Population'].fillna(0, inplace=True)
worldometer_data['Tot Cases/1M pop'].fillna(0, inplace=True)
worldometer_data['Deaths/1M pop'].fillna(0, inplace=True)
worldometer_data['Tests/1M pop'].fillna(0, inplace=True)

/tmp/ipykernel_582/638249284.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  worldometer_data['Population'].fillna(0, inplace=True)
/tmp/ipykernel_582/638249284.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  worldometer_data['Tot Cases/1M pop'].fillna(0, inplace=True)
/tmp/ipykernel_582/638249284.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  worldometer_data['Deaths/1M pop'].fillna(0, inplace=True)
/tmp/ipykernel_582/638249284.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  worldometer_data['Tests/1M pop'].fillna(0, inplace=True)

In [9]:
worldometer_data.isna().sum()

Country/Region      0
Continent           0
Population          0
TotalCases          0
NewCases            0
TotalDeaths         0
NewDeaths           0
TotalRecovered      0
NewRecovered        0
ActiveCases         0
Serious,Critical    0
Tot Cases/1M pop    0
Deaths/1M pop       0
TotalTests          0
Tests/1M pop        0
WHO Region          0
dtype: int64

In [11]:
worldometer_data[worldometer_data['Country/Region'] == "Diamond Princess"]

,Country/Region,Continent,Population,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/1M pop,WHO Region
156,Diamond Princess,Unknown,0.0,712,0.0,13.0,0.0,651.0,0.0,48.0,4.0,0.0,0.0,0.0,0.0,Unknown

The rest of the null values left on diamond princess are filled with .fillna(0, inplace=True), as the ship has 0 death per population.

## Checking Duplicated Data

This section will check if the dataframes include duplicated values.

In [13]:
ccbd_visualization.duplicated().sum()

np.int64(0)

In [14]:
ccbd_country.duplicated().sum()

np.int64(0)

In [15]:
ccpc.duplicated().sum()

np.int64(0)

In [16]:
symptoms.duplicated().sum()

np.int64(0)

In [17]:
iso.duplicated().sum()

np.int64(0)

In [18]:
worldometer_data.duplicated().sum()

np.int64(0)

Every rows in the dataset are unique.

## Data Anomalies Check
This section will check if there are odd data among the dataset, such as dates from the future or extraordinary amount of statistics.

In [19]:
# Getting today date, date from dataframe and formatting to same format (for date checks)
today = datetime.now()
formatted_today = today.strftime("%m/%d/%Y")

### Covid cases by day (visualization)

In [20]:
ccbd_visualization.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188 entries, 0 to 187
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    188 non-null    object
 1   Confirmed               188 non-null    int64
 2   Deaths                  188 non-null    int64
 3   Recovered               188 non-null    int64
 4   Active                  188 non-null    int64
 5   New cases               188 non-null    int64
 6   New deaths              188 non-null    int64
 7   New recovered           188 non-null    int64
 8   Deaths / 100 Cases      188 non-null    float64
 9   Recovered / 100 Cases   188 non-null    float64
 10  Deaths / 100 Recovered  188 non-null    float64
 11  No. of countries        188 non-null    int64
dtypes: float64(3), int64(8), object(1)
memory usage: 17.8+ KB

#### Date Check

In [21]:
ccbd_visualization['Date'] = pd.to_datetime(ccbd_visualization['Date'],
                                            format='%m/%d/%Y')

# Checking date error
date_error = ccbd_visualization[ccbd_visualization['Date'] > formatted_today]
print("The number of dates that are out of range from today date:" ,
      len(date_error))

The number of dates that are out of range from today date: 0

Non of the date exceed the current date which means the dates are correct.

#### Confirmed Check
Based on looking at the dataframe of covid cases by day, the confirmed value should be the sum of deaths, recovered, and active values.

In [22]:
confirmed_error = ccbd_visualization[ccbd_visualization['Confirmed'] !=
                                     (ccbd_visualization['Deaths'] +
                                      ccbd_visualization['Recovered'] +
                                      ccbd_visualization['Active'])]
print("The number of confirmed deaths that doesn't match the sum of deaths, recovered, and active:", len(confirmed_error))

The number of confirmed deaths that doesn't match the sum of deaths, recovered, and active: 0

#### Number of countries

In [23]:
# Checking how many countries are in the data collection
len(ccbd_visualization['No. of countries'].unique())

56

### Covid cases by day and country

In [24]:
ccbd_country.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35156 entries, 0 to 35155
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            35156 non-null  object
 1   Country/Region  35156 non-null  object
 2   Confirmed       35156 non-null  int64
 3   Deaths          35156 non-null  int64
 4   Recovered       35156 non-null  int64
 5   Active          35156 non-null  int64
 6   New cases       35156 non-null  int64
 7   New deaths      35156 non-null  int64
 8   New recovered   35156 non-null  int64
 9   WHO Region      35156 non-null  object
dtypes: int64(7), object(3)
memory usage: 2.7+ MB

#### Date Check

In [25]:
ccbd_country['Date'] = pd.to_datetime(ccbd_country['Date'],
                                      format = '%m/%d/%Y')

# Checking date error
date_error = ccbd_country[ccbd_country['Date'] > formatted_today]
print("The number of date in dataset that exceed today's date:", len(date_error))

The number of date in dataset that exceed today's date: 0

#### Confirmed Check

In [26]:
confirmed_error_2 = ccbd_country[ccbd_country['Confirmed'] !=
                                 ccbd_country['Deaths'] +
                                 ccbd_country['Recovered'] +
                                 ccbd_country['Active']]
print("The number of confirmed error in dataset that exceed the sum:", len(confirmed_error_2))

The number of confirmed error in dataset that exceed the sum: 0

### Covid Cases per country

In [27]:
ccpc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Country/Region          187 non-null    object
 1   Confirmed               187 non-null    int64
 2   Deaths                  187 non-null    int64
 3   Recovered               187 non-null    int64
 4   Active                  187 non-null    int64
 5   New cases               187 non-null    int64
 6   New deaths              187 non-null    int64
 7   New recovered           187 non-null    int64
 8   Deaths / 100 Cases      187 non-null    float64
 9   Recovered / 100 Cases   187 non-null    float64
 10  Deaths / 100 Recovered  187 non-null    float64
 11  Confirmed last week     187 non-null    int64
 12  1 week change           187 non-null    int64
 13  1 week % increase       187 non-null    float64
 14  WHO Region              187 non-null    object
dtypes: float64(4), int64(9), object(2)
memory usage: 22.0+ KB

In [28]:
# Confirmed Checking
covidCasesPerCountry_error = ccpc[ccpc['Confirmed'] != ccpc['Deaths'] +
                                  ccpc['Recovered'] + ccpc['Active']]
print("The number of covid cases per country error:", len(covidCasesPerCountry_error))

The number of covid cases per country error: 0

### Symptoms Check

In [29]:
symptoms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 316800 entries, 0 to 316799
Data columns (total 27 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Fever                    316800 non-null  int64
 1   Tiredness                316800 non-null  int64
 2   Dry-Cough                316800 non-null  int64
 3   Difficulty-in-Breathing  316800 non-null  int64
 4   Sore-Throat              316800 non-null  int64
 5   None_Sympton             316800 non-null  int64
 6   Pains                    316800 non-null  int64
 7   Nasal-Congestion         316800 non-null  int64
 8   Runny-Nose               316800 non-null  int64
 9   Diarrhea                 316800 non-null  int64
 10  None_Experiencing        316800 non-null  int64
 11  Age_0-9                  316800 non-null  int64
 12  Age_10-19                316800 non-null  int64
 13  Age_20-24                316800 non-null  int64
 14  Age_25-59                316800 non-null  int64
 15  Age_60+                  316800 non-null  int64
 16  Gender_Female            316800 non-null  int64
 17  Gender_Male              316800 non-null  int64
 18  Gender_Transgender       316800 non-null  int64
 19  Severity_Mild            316800 non-null  int64
 20  Severity_Moderate        316800 non-null  int64
 21  Severity_None            316800 non-null  int64
 22  Severity_Severe          316800 non-null  int64
 23  Contact_Dont-Know        316800 non-null  int64
 24  Contact_No               316800 non-null  int64
 25  Contact_Yes              316800 non-null  int64
 26  Country                  316800 non-null  object
dtypes: int64(26), object(1)
memory usage: 65.3+ MB

In [30]:
len(symptoms['Country'].unique())

10

In [31]:
symptoms['Country'].unique()

array(['China', 'Italy', 'Iran', 'Republic of Korean', 'France', 'Spain',
       'Germany', 'UAE', 'Other-EUR', 'Other'], dtype=object)

## Downloading Cleaned Datasets

In [36]:
# Downloading datasets
ccbd_visualization.to_csv('Cleaned Covid Cases by day (Visualization).csv', index=False)
ccbd_country.to_csv('Cleaned Covid Cases by day and country.csv', index=False)
ccpc.to_csv('Cleaned Covid Cases per country.csv', index=False)
symptoms.to_csv('Cleaned Covid Symptoms.csv', index=False)
iso.to_csv('Cleaned ISO.csv', index=False)
worldometer_data.to_csv('Cleaned Worldometer Data.csv', index=False)

In [37]:
files.download('Cleaned Covid Cases by day (Visualization).csv')
files.download('Cleaned Covid Cases by day and country.csv')
files.download('Cleaned Covid Cases per country.csv')
files.download('Cleaned Covid Symptoms.csv')
files.download('Cleaned ISO.csv')
files.download('Cleaned Worldometer Data.csv')